[workspace]

resolver = "2"
members = [
    "fritz-app",
    "fritz-api",
]

[profile.release]
strip = true
panic = "abort"

# https://github.com/launchbadge/sqlx/tree/main#compile-time-verification
[profile.dev.package.sqlx-macros]
opt-level = 3
